name: ðŸ”‘ Obtener archivo de licencia de Unity

on:
  workflow_dispatch: # Te permite ejecutarlo manualmente

jobs:
  activation:
    name: Obtener archivo .alf
    runs-on: ubuntu-latest
    steps:
      # 1. Pide el archivo de activaciÃ³n (.alf)
      - name: Request activation file
        id: get-alf
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2023.2.1f1 # âš ï¸ Â¡CAMBIA ESTO a tu versiÃ³n exacta!

      # 2. Sube el .alf para que puedas descargarlo
      - name: Upload .alf
        uses: actions/upload-artifact@v4 # âš ï¸ Â¡AQUÃ ESTÃ EL CAMBIO! (v3 -> v4)
        with:
          name: Unity-Activation-File
          path: ${{ steps.get-alf.outputs.filePath }}